### ISSUE TITLE
Custom types

### ISSUE THREAD

**Issue by semuelle** [logion-network/logion-wallet#282]
The referenced file doesn't exist. Did you mean https://github.com/logion-network/logion-node/blob/main/additional-types.json?

https://github.com/logion-network/logion-wallet/blob/23d56451b33cd96c9999389a2a81696c8a0bc5ac/README.md?plain=1#L69

**Comment by gdethier** [comment]
@semuelle Thanks for reporting and sorry for the delay, the issue somehow went unnoticed up to now. The `additional-types.json` file and `definitions.ts` are equivalent. And indeed, `definitions.ts` does not exist anymore in the project because we are in the process of producing an SDK encapsulating the interactions with our REST API and nodes (see https://github.com/logion-network/logion-api). Also, I see that there is no need anymore to register custom types manually in Polkadot.js (the tab is even gone).

I'll fix the README.
